### ISSUE TITLE
incompatible encoding regexp match (Windows-31J regexp with UTF-8 string)

### ISSUE THREAD

**Issue by sandiegoscott** [amsardesai/middleman-protect-emails#2]
That's the error I got with version 0.3.0 of middleman-protect-emails and the latest version of everything else. Change the version to

```
gem 'middleman-protect-emails', '~> 0.2.0'
```

and the error goes away. My 'mailto:' lines are extremely ordinary Haml:

```
%a{:href=>"mailto:info@mywebsite.com", :target => "_blank"}
```

The errors occurred with three files. Two were test or Markdown files in jQuery plugins, so I removed those rather than track down the problem character(s).

The last was in an ordinary page. I tracked it down painfully to the inclusion on this:

```
   they’ve
```

in some Frontmatter data, where that apostrophe was copied from a web page or an email or something. When it is replaced with as ASCII ' then the error goes away.

I spent so much on this I had to tell someone. I used pry on the gem code, but the content of the 'body' variable on line 48 of extension.rb was so large it was impossible to work with. I ended up doing a binary search on the source, removing smaller and smaller sections of files. Tedious, but effective.

Is there a way that the gem could find the bad character and display it to save the next person this quest?

**Comment by amsardesai** [comment]
Thank you for bringing this up. This gem uses regular expressions to search for matching mailto links, and it seems one of the regular expressions in my code had a `/s` flag (more info here: http://ruby-doc.org/core-2.2.0/Regexp.html#class-Regexp-label-Encoding), which is a flag for strings encoded in a very special breed of Unicode (Windows 31-J). Since most people use UTF-8 and not Windows 31-J, I'm going to release a patch to fix this. Once again thanks for reporting this!
